DROP TABLE ACCOUNT;
DROP TABLE CHARGED;
DROP TABLE TYPEVEHICLE;
DROP TABLE REGISTRATION;
DROP TABLE VEHICLE;
DROP TABLE VIOLATION;
DROP TABLE VIO_FIN;
DROP TABLE FINE;

DROP SEQUENCE ACCOUNT_SEQ;
DROP SEQUENCE VIOLATION_SEQ;
DROP SEQUENCE TYPEVEHICLE_SEQ;