CREATE TABLE ACCOUNT
(
	IDACCOUNT				NUMBER 					NOT NULL,
	TYPEACCOUNT				VARCHAR(50) 			NOT NULL,
	PERSONELNUMBER			VARCHAR(50) 			NOT NULL,
	PASSWORD				VARCHAR(50) 			NOT NULL
);

CREATE TABLE FINE
(
	IDFINE 				NUMBER 			NOT NULL,
	DATEFINE  			DATE 			NOT NULL,
	COMMENTFINE 		varchar(500) 	NOT NULL,
	VALIDATED 			NUMBER(1)		NOT NULL,
	IDVEHICLE			NUMBER			NOT NULL,
	IDCHARGED			NUMBER			NOT NULL,
	IDACCOUNT			NUMBER			NOT NULL
);
	
CREATE TABLE VIOLATION
(
	IDVIOLATION 			NUMBER 					NOT NULL,
	NAME 					VARCHAR2(50)			NOT NULL,
	PRICE 					NUMBER 					NOT NULL,
	DESCRIPTION 			VARCHAR2(500) 			NOT NULL
);

CREATE TABLE VIO_FIN
(
	IDVIOLATION 				NUMBER,
	IDFINE 						NUMBER
);

CREATE TABLE CHARGED
(
	IDCHARGED 			NUMBER 			NOT NULL,
	FIRSTNAME 			varchar(50) 	NOT NULL,
	LASTNAME 			varchar(50) 	NOT NULL,
	ADDRESS 			varchar(50) 	NOT NULL
);

CREATE TABLE VEHICLE
(
	IDVEHICLE 			NUMBER			NOT NULL,
	IDTYPE				NUMBER			NOT NULL,
	IDREGISTRATION		NUMBER			NOT NULL
);

CREATE TABLE TYPEVEHICLE
(
	IDTYPE 			NUMBER,
	NAME 			VARCHAR2(50)
);

CREATE TABLE REGISTRATION
(
	IDREGISTRATION 		NUMBER 			NOT NULL,
	SERIALNUMBER 		varchar(50) 	NOT NULL
);

	
ALTER TABLE ACCOUNT ADD
	PRIMARY KEY(IDACCOUNT) 
	ADD CONSTRAINTS PERSONELNUMBER_UNIQUE UNIQUE (PERSONELNUMBER)
;

ALTER TABLE FINE ADD
	PRIMARY KEY(IDFINE)
;
ALTER TABLE VIOLATION ADD
	PRIMARY KEY(IDVIOLATION)
;
ALTER TABLE VEHICLE ADD
	PRIMARY KEY(IDVEHICLE)
;
ALTER TABLE REGISTRATION ADD
	PRIMARY KEY(IDREGISTRATION)
;
ALTER TABLE TYPEVEHICLE ADD
	PRIMARY KEY(IDTYPE)
;
ALTER TABLE CHARGED ADD
	PRIMARY KEY(IDCHARGED)
;
ALTER TABLE VIO_FIN ADD
	FOREIGN KEY (IDVIOLATION)
		REFERENCES VIOLATION(IDVIOLATION)
;
ALTER TABLE VIO_FIN ADD
	FOREIGN KEY (IDFINE)
		REFERENCES FINE(IDFINE)
;
ALTER TABLE Fine ADD
	FOREIGN KEY (IDVEHICLE)
		REFERENCES VEHICLE(IDVEHICLE)
;
ALTER TABLE Fine ADD
	FOREIGN KEY (IDCHARGED)
		REFERENCES CHARGED(IDCHARGED)
;
ALTER TABLE Fine ADD
	FOREIGN KEY (IDACCOUNT)
		REFERENCES ACCOUNT(IDACCOUNT)
;
ALTER TABLE VEHICLE ADD
	FOREIGN KEY (IDTYPE)
		REFERENCES TYPEVEHICLE(IDTYPE)
;
ALTER TABLE VEHICLE ADD
	FOREIGN KEY (IDREGISTRATION)
		REFERENCES REGISTRATION(IDREGISTRATION)
;

CREATE SEQUENCE ACCOUNT_SEQ;